---
title: "Publications"
---

::: callout-note
\* = equal contribution/co-first
:::

## Peer-reviewed articles

### First-author publications

1.  **Zhao A**, Cui E, Leroux A, Zhou X, Muschelli J, Lindquist M, Crainiceanu CM (2024) Objectively measured physical activity using wrist-worn accelerometers as a predictor of incident Alzheimer’s Disease in the UK Biobank. *The Journals of Gerontology. Series A, Biological sciences and medical sciences*, glae287. Advance online publication. https://doi.org/10.1093/gerona/glae287

2.  **Zhao A**, Cui E, Leroux A, Lindquist M, Crainiceanu CM (2023). Evaluating the prediction performance of objective physical activity measures for incident Parkinson’s disease in the UK Biobank. *Journal of Neurology,* 270(12), 5913–5923. https://doi.org/10.1007/s00415-023-11939-0

3.  Cui E\*, **Zhao A\*** , Crainiceanu C, Leroux A. Inference for the Extended Functional Cox Model: A UK Biobank Case Study *(submitted to Statistics in Medicine)*.

4.  **Zhao A**, Lindquist M, Caffo B. Comparing stochastic model performance with applications to fMRI data *(in preparation)*.

### Other publications

5. Goeddel LA, Koffman L, Zhou X, Hernandez M, **Zhao A**, Pasrija C, Saha AK, Muschelli J, Parikh CR, Crainiceanu CM, Brown C IV, Khanna AK, Faraday N (2026). Low cardiac index during periods of arterial hypotension and risk of acute kidney injury in cardiac surgery. *British Journal of Anaesthesia*. Advance online publication. https://doi.org/10.1016/j.bja.2026.02.037

6. Lindquist M A, Smith B B, Kannan A, **Zhao A**, Caffo B (2025). Measuring the Functioning Human Brain. Annual Review of Statistics and its Application,. https://doi.org/10.1146/annuarev-statistics-040522-100329

7.  Morelli K, Meier SM, Choudhury M, **Zhao A**, Willis M, Barral M, Vogel J (2025). A fluid droplet harvests the force generated by shrinking microtubules in living cells *(accepted by Cell Biology)*.

8.  Wanigatunga AA, Dong Y, Jin M, Leroux A, Cui, E, Zhou X, **Zhao A**, Schrack JA, Bandeen Roche K, Walston J, Xue QL, Lindquist MA, Crainiceanu CM (2024). Moderate-to-Vigorous Physical Activity at Any Dose Reduces All-Cause Dementia Risk Regardless of Frailty Status. JAMDA. Accepted on 12.2.2024.

## Presentations

1. **Zhao A**, Cui E, Leroux A, Lindquist M, Crainiceanu C (November 2026). Objectively Measured Physical Activity Using Wrist-Worn Accelerometers. **Invited symposium presentation**, *Journal of Gerontology, Series A: Medical Sciences* Editor's Choice Symposium: "From Pages to Paradigms," Gerontological Society of America Annual Scientific Meeting, Baltimore, MD.

1.  **Zhao A**, Cui E, Leroux A, Lindquist M, Crainiceanu C (August 2025). Data-Driven Risk Prediction of Alzheimer’s Disease Using Device-Measured Physical Activity and Robust Variable Selection. **Invited session presentation** for *Joint Statistical Meetings*, Nashville TN.

2.  **Zhao A**, Cui E, Leroux A, Lindquist M, Crainiceanu C (March 2025). Inference for the Extended Functional Cox Model: A UK Biobank Case Study. Contributed session for *ENAR International Biometric Society*, New Orleans LA.

3.  **Zhao A**, Cui E, Leroux A, Lindquist M, Crainiceanu C (May 2024). Predicting Time-To-Event Incidence of Alzheimer’s Disease and Mortality using Objective Physical Activity Measures in the UK Biobank, *10th Annual Joint Session of the BHS Lab, ENGAGE Lab, and SMART-WIT groups*, Johns Hopkins Univeristy, Baltimore MD.

4.  Sim S, Morelli K, **Zhao A**, Vogel J (May 2023). L'effet de la phosphorylation de la tubuline-y sur la kinésine-5 et sur la formation de paires de microtubules dans le fuseau mitotique, *90e Congrès de l’ACFAS*, Université de Montréal, Montréal Canada.

5.  **Zhao A**, Cui E, Leroux A, Lindquist M, Crainiceanu C, (April 2023). Physical activity to predict Parkinson's disease in the UK Biobank, *8th Annual Joint Session of the BHS Lab, ENGAGE Lab, and SMART-WIT groups*, Johns Hopkins Univeristy, Baltimore MD.

6.  Sim S, Morelli K, **Zhao A**, Vogel J, (May 2022). Le rôle de la phosphorylation de la tubuline-y dans l’organisation des microtubules du fuseau mitotique médiée par la kinésine-5, *89e Congrès de l’ACFAS*, Université de Montréal, Montréal Canada.

## Posters and Abstracts

7.  Morelli K, Meier SM, **Zhao A**, Willis M, Barral Y, Vogel J, (2023). Interrogating the material properties of a microtubule (+) end-associated nanoscale condensate in living cells using super-resolution microscopy, *American Society for Cell Biology Cell Bio Virtual*.

8.  Sim S, **Zhao A**, Vogel J (2023). Phosphoregulation of y-tubulin regulates anti-parallel microtubule bundling through kinesin-5, *8th Meeting of the International Union of Microbeam Analysis Societies*.

9.  Sim S, **Zhao A**, Vogel J (2023). y-Tubulin phosphoregulation controls interpolar microtubule organization through kinesin-5, *Mitotic spindle: From living and synthetic systems to theory*.

10. Sim S, Morelli K, **Zhao A**, Vogel J (2022). How does y-tubulin phosphoregulation control microtubule identity during spindle assembly?, *4th Annual CRBS Symposium*, Montréal, Canada.

11. Sim S, Morelli K, **Zhao A**, Vogel J (2021). Phosphoregulation of y-Tubulin Directs Spindle Assembly Through Kinesin-5 and Microtubule Number, *American Society for Cell Biology Cell Bio Virtual*.
