---
title: "Work Experience"
editor: source
---

\comment{TODO: make personal projects tab.
Caffo: Firehouse, EP test
Crainiceanu: cardiac surgery, fcox testing, mpog drug, digital twin}

## Research Positions

**Currently working on a tool to forecast call volume in collaboration with the Owings Mills Volunteer Firehouse to address staffing demands.**

**Emerald Advisors, LLC \|** *Life Sciences Research Analyst Intern* \| May 2024 - Aug. 2024

-   Assisted senior analysts in covering 20+ biotech/therapeutics companies at a long-only firm managing ∼\$5B of AUM.

-   Evaluated scientific literature, clinical trial data, and business filings as part of the due diligence process for new ideas.

-   Contributed to the BUY decision on a stock that went up 50+% and made a positive 8bps impact to the portfolio.

-   Conducted due diligence for an IPO, including constructing comps tables and reviewing SEC-1 filings.

**Johns Hopkins University, Wearable and Implantable Technology Group** \| *Research Associate for Dr. Ciprian Crainiceanu* \| Sep. 2022 - Present

-   Helped develop inference procedures for functional cox models that consider the inherent correlation of timeseries data.

-   Demonstrated that wearable device metrics improve the performance of traditional survival models by up to 10%.

-   Produced robust R pipelines for analyzing high-dimensional data on a cluster computer (N = 500, 000, p \> 1000).

-   This work resulted in 1 peer-reviewed paper Springer Journal of Neurology and 3 papers under revision.

**Johns Hopkins University, Department of Biostatistics** \| *Research Assistant for Dr. Brian Caffo* \| Jul. 2023 - May 2024

-   Comprehensively compared stochastic timeseries models to capture the complex dynamics of real/simulated fMRI data.

-   Leveraged the Pytorch, Tensorflow, and Keras libraries in Python to tune and test RNNs, transformers, and AR models.

-   Proposed that the potency of transformers suggest a form of neural context that challenges standard fMRI assumptions.

-   This work resulted in 1 peer-reviewed review article in Annual Reviews of Statistics and 1 paper under revision.

**McGill University, Quantitative Life Sciences** \| *Research Assistant for Dr. Jackie Vogel* \| Jan. 2020 - Aug. 2022 - Developed shape analysis pipelines in Java and Python to identify droplet-like behaviours in proteins from video data.

-   Leveraged ML for artifact removal and signal processing; weighted-mean/Gaussian approaches for subpixel positioning.

-   Contributed to single-cell analysis software for super-resolution image data that lead to 8+ talks, posters, and abstracts.

## Editorial Activities – Peer Reviewer

*Journal of Neurology (1)*

*Biostatistics and Epidemiology (2)*

## Teaching Positions

**Johns Hopkins University**

Teaching Assistant \| Advanced Data Science I & II, ∼10 students \| 2025

Teaching Assistant \| Statistical Programming Paradigms and Workflows, ∼45 students \| 2023

Teaching Assistant \| Statistical Methods in Public Health II, ∼300 students \| 2023

Teaching Assistant \| Statistical Machine Learning, ∼50 students \| 2023

**McGill University**

Undergraduate Tutor \| Subjects: Discrete Maths, Algorithms and Data Structures, Organic Chemistry I, and more. \| ∼10 students \| 2020-2022

Teaching Assistant \| Data Science, ∼200 students \| 2021

TEAM Mentor \| Physics - Electromagnetism \| Tutorials and Office Hours \~200 students \| 2021

TEAM Mentor \| General Chemistry 1 \| Tutorials and Office Hours \~200 students \| 2020

Grader \| Introduction to Biophysics, ∼150 students \| 2020

## Leadership Positions

**Johns Hopkins University**

Doctoral Student Council \| *Biostatistics Representative* \| 2025-2026

Department of Biostatistics \| *ScM Student-Faculty Representative* \| 2023-2024

Biostatistics Students Organization \| *Curriculum Committee Representative* \| 2023-2024

*CEPH Site Visit Student Representative* \| For reaccreditation from the Council on Education for Public Health \| 2023

**McGill University**

*President* \| McGill Integrative Biosciences Society \| 2021-2022

*VP Events* \| McGill Integrative Biosciences Society \| 2020-2021

\comment{## Miscellaneous Positions}

}

}
